[package]
name = "hive"
version.workspace = true
edition.workspace = true

[dependencies]
hive-api.workspace = true
hive-config.workspace = true
hive-database.workspace = true
hive-error.workspace = true
axum.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
