[package]
name = "brier-workspace"
version.workspace = true
edition.workspace = true

[dependencies]
brier-error.workspace = true
brier-type.workspace = true
sea-orm.workspace = true
chrono.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
