[package]
name = "brier-api"
version.workspace = true
edition.workspace = true

[dependencies]
brier-core.workspace = true
brier-contract = { workspace = true, features = ["openapi"] }
brier-error.workspace = true
brier-config.workspace = true
brier-crypto.workspace = true
brier-forge.workspace = true
brier-workspace.workspace = true
brier-agent.workspace = true
brier-type = { workspace = true, features = ["openapi"] }
brier-user.workspace = true
brier-jwt.workspace = true
brier-tunnel.workspace = true
axum.workspace = true
futures.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
cookie.workspace = true
tracing.workspace = true
sea-orm.workspace = true
chrono.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
