/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Brier API
 * AI Agent 工作空间平台
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from './custom-instance';
/**
 * 用户唯一标识
 */
export type UserId = string;

/**
 * Agent 唯一标识
 */
export type AgentId = string;

export type AgentStatus = typeof AgentStatus[keyof typeof AgentStatus];


export const AgentStatus = {
  online: 'online',
  offline: 'offline',
  connecting: 'connecting',
} as const;

export type AgentVisibility = typeof AgentVisibility[keyof typeof AgentVisibility];


export const AgentVisibility = {
  private: 'private',
  public_all: 'public_all',
  public_joined_spaces: 'public_joined_spaces',
  public_specified_spaces: 'public_specified_spaces',
} as const;

/**
 * 工作电脑唯一标识
 */
export type WorkComputerId = string;

/**
 * 工作空间唯一标识
 */
export type WorkspaceId = string;

export interface Agent {
  /** @nullable */
  avatar?: string | null;
  /** 并发数（创建时默认 3，当前无修改入口；存档/展示语义）。 */
  concurrency: number;
  created_at: string;
  creator_id: UserId;
  /** @nullable */
  description?: string | null;
  id: AgentId;
  /** @nullable */
  last_active?: string | null;
  /**
     * 显式指定的模型名；空（NULL）表示不指定、由 runtime 自己决定。
     * @nullable
     */
  model?: string | null;
  name: string;
  /** @nullable */
  runtime?: string | null;
  status: AgentStatus;
  updated_at: string;
  visibility: AgentVisibility;
  work_computer_id?: null | WorkComputerId;
  /**
     * 绑定的工作电脑名（冗余字段，绑定/换绑时随 id 一起写入，便于详情页展示）。
     * @nullable
     */
  work_computer_name?: string | null;
  /**
     * Agent 任务执行的工作目录（daemon 在该目录 spawn runtime），空则继承 daemon 目录。
     * @nullable
     */
  workdir?: string | null;
  workspace_id: WorkspaceId;
}

/**
 * Agent 任务唯一标识
 */
export type TaskId = string;

export type TaskPriority = typeof TaskPriority[keyof typeof TaskPriority];


export const TaskPriority = {
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;

export type TaskSource = typeof TaskSource[keyof typeof TaskSource];


export const TaskSource = {
  manual: 'manual',
  automation: 'automation',
} as const;

export type TaskStatus = typeof TaskStatus[keyof typeof TaskStatus];


export const TaskStatus = {
  pending: 'pending',
  running: 'running',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

/**
 * Agent 任务：把指令下发给绑定工作电脑上的 runtime 执行，输出聚合回传。
 */
export interface AgentTask {
  agent_id: AgentId;
  /**
     * 自定义 shell 命令（有值时绕过 runtime 直接执行，高级用法）。
     * @nullable
     */
  command?: string | null;
  computer_id?: null | WorkComputerId;
  created_at: string;
  creator_id: UserId;
  /** @nullable */
  error?: string | null;
  /** @nullable */
  exit_code?: number | null;
  /** @nullable */
  finished_at?: string | null;
  id: TaskId;
  /** 聚合输出（stdout/stderr 按到达顺序追加）。 */
  output: string;
  priority: TaskPriority;
  /**
     * 发给 runtime 的自然语言指令（AI runtime 模式下作为 CLI 参数）。
     * @nullable
     */
  prompt?: string | null;
  /** @nullable */
  runtime?: string | null;
  source: TaskSource;
  /** @nullable */
  started_at?: string | null;
  status: TaskStatus;
  title: string;
  updated_at: string;
  workspace_id: WorkspaceId;
}

/**
 * Agent 团队唯一标识
 */
export type AgentTeamId = string;

export type TeamMode = typeof TeamMode[keyof typeof TeamMode];


export const TeamMode = {
  coordinator: 'coordinator',
  sequential: 'sequential',
  graph: 'graph',
} as const;

export type TeamStatus = typeof TeamStatus[keyof typeof TeamStatus];


export const TeamStatus = {
  available: 'available',
  unavailable: 'unavailable',
} as const;

export interface AgentTeam {
  created_at: string;
  creator_id: UserId;
  /** @nullable */
  description?: string | null;
  id: AgentTeamId;
  mode: TeamMode;
  name: string;
  primary_agent_id?: null | AgentId;
  status: TeamStatus;
  updated_at: string;
  workspace_id: WorkspaceId;
}

export type MessageRole = typeof MessageRole[keyof typeof MessageRole];


export const MessageRole = {
  user: 'user',
  agent: 'agent',
} as const;

export interface AppendMessageRequest {
  agent_id?: null | AgentId;
  content: string;
  role: MessageRole;
  task_id?: null | TaskId;
}

/**
 * 接入令牌响应：原文只在生成时返回一次，服务端仅存哈希。
 */
export interface ConnectTokenResponse {
  token: string;
}

export interface CreateAgentRequest {
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  description?: string | null;
  /**
     * 显式模型名；缺省/null = 不指定，由 runtime 自己决定。
     * @nullable
     */
  model?: string | null;
  name: string;
  /** @nullable */
  runtime?: string | null;
  visibility?: null | AgentVisibility;
  /** @nullable */
  work_computer_id?: string | null;
}

export interface CreateSessionRequest {
  agent_id: AgentId;
  /** 首条用户消息（同时作为会话默认标题来源）。 */
  first_message: string;
  /** @nullable */
  title?: string | null;
}

export interface CreateTaskRequest {
  agent_id: AgentId;
  /**
     * 显式 shell 命令（高级用法，绕过 runtime；prompt 与 command 至少其一）。
     * @nullable
     */
  command?: string | null;
  /**
     * 执行形态：pty（交互，可回答提问）/ pipe（非交互，默认）。
     * @nullable
     */
  exec_mode?: string | null;
  priority?: null | TaskPriority;
  /**
     * 自然语言指令（AI runtime 模式：CLI 会拼成该 runtime 的执行参数）。
     * @nullable
     */
  prompt?: string | null;
  /**
     * 续接的 CLI 会话 ID（如 opencode session，由前端从上一轮事件解析后回传）；缺省不续接。
     * @nullable
     */
  resume_session_id?: string | null;
  title: string;
}

export interface CreateTeamRequest {
  /** @nullable */
  description?: string | null;
  mode?: null | TeamMode;
  name: string;
  /** @nullable */
  primary_agent_id?: string | null;
}

export type WorkComputerType = typeof WorkComputerType[keyof typeof WorkComputerType];


export const WorkComputerType = {
  local: 'local',
  ssh: 'ssh',
  cloud: 'cloud',
} as const;

export interface CreateWorkComputerRequest {
  computer_type: WorkComputerType;
  host: string;
  name: string;
  os: string;
}

export interface CreateWorkspaceRequest {
  /** @nullable */
  auto_issue_assign?: boolean | null;
  /** @nullable */
  auto_pr_review?: boolean | null;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  instructions?: string | null;
  name: string;
  /** @nullable */
  repositories?: string[] | null;
  slug: string;
}

/**
 * 代码仓库信息（厂商 API 返回的仓库视图，非 Brier 领域概念）。
 * 与 `RepositoryProvider` 强绑定（trait 方法签名引用），故随契约同居本包；
 * 消费方仅限适配层（brier-forge）与应用层（brier-api）两端，不进 brier-type。
 */
export interface RepoInfo {
  full_name: string;
  name: string;
  private: boolean;
}

/**
 * 会话唯一标识
 */
export type SessionId = string;

/**
 * 会话：用户与 Agent 围绕任务的对话记录（对应一列消息）。
 */
export interface Session {
  agent_id: AgentId;
  created_at: string;
  creator_id: UserId;
  id: SessionId;
  title: string;
  updated_at: string;
  workspace_id: WorkspaceId;
}

/**
 * 会话消息唯一标识
 */
export type SessionMessageId = string;

/**
 * 会话消息：一条 user 指令或一条 agent 回复（可与任务关联）。
 */
export interface SessionMessage {
  agent_id?: null | AgentId;
  content: string;
  created_at: string;
  id: SessionMessageId;
  role: MessageRole;
  session_id: SessionId;
  task_id?: null | TaskId;
}

/**
 * Agent 字段级更新（缺省字段保持不变；model 传 null 表示清空为"由 runtime 决定"）。
 */
export interface UpdateAgentRequest {
  /** @nullable */
  avatar?: string | null;
  /**
     * 并发数；缺省 = 保持不变（创建默认 3，创建接口不暴露该字段）。
     * @nullable
     */
  concurrency?: number | null;
  /** @nullable */
  description?: string | null;
  /**
     * 显式模型名；null = 清空（由 runtime 决定），缺省 = 保持不变。
     * @nullable
     */
  model?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  runtime?: string | null;
  visibility?: null | AgentVisibility;
  /** @nullable */
  work_computer_id?: string | null;
  /**
     * 任务执行工作目录（daemon 在该目录 spawn runtime）。
     * @nullable
     */
  workdir?: string | null;
}

export type UserStatus = typeof UserStatus[keyof typeof UserStatus];


export const UserStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;

/**
 * 账户本体。第三方身份（OAuth）与本地凭证（手机号/密码）统一挂载在
 * `id`（用户 UUID）之下；password_hash 属敏感凭证，永不进入该 API 模型。
 */
export interface User {
  /** @nullable */
  avatar_url?: string | null;
  created_at: string;
  /** @nullable */
  email?: string | null;
  id: UserId;
  /** @nullable */
  last_login_at?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  phone?: string | null;
  /**
     * 最近登录绑定的第三方身份（如 github / gitee）；本地凭证账户为 None。
     * @nullable
     */
  provider?: string | null;
  status: UserStatus;
  updated_at: string;
  username: string;
}

export type WorkComputerStatus = typeof WorkComputerStatus[keyof typeof WorkComputerStatus];


export const WorkComputerStatus = {
  online: 'online',
  offline: 'offline',
} as const;

export interface WorkComputer {
  computer_type: WorkComputerType;
  created_at: string;
  host: string;
  id: WorkComputerId;
  /** @nullable */
  last_seen_at?: string | null;
  name: string;
  os: string;
  /** 电脑上可用的运行时（CLI 探测上报，如 ["OpenCode", "Node.js"]）。 */
  runtimes: string[];
  status: WorkComputerStatus;
  updated_at: string;
  user_id: UserId;
  /**
     * 接入 CLI（brier daemon）版本号。
     * @nullable
     */
  version?: string | null;
}

export interface Workspace {
  auto_issue_assign: boolean;
  auto_pr_review: boolean;
  /** @nullable */
  avatar?: string | null;
  created_at: string;
  creator_id: UserId;
  /** @nullable */
  description?: string | null;
  id: WorkspaceId;
  /** @nullable */
  instructions?: string | null;
  name: string;
  repositories: string[];
  slug: string;
  updated_at: string;
}

export type ProviderCallbackParams = {
/**
 * OAuth 授权码（OAuth 回调携带的 query 参数）。
 */
code: string;
};

export const getLogoutUrl = () => {




  return `/api/auth/logout`
}

/**
 * @summary 登出：清除会话 Cookie 并跳转首页。
 */
export const logout = async ( options?: Parameters<typeof customFetch>[1]): Promise<unknown> => {

  return customFetch<unknown>(getLogoutUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getAuthMeUrl = () => {




  return `/api/auth/me`
}

/**
 * @summary 返回当前登录用户信息。
 */
export const authMe = async ( options?: Parameters<typeof customFetch>[1]): Promise<User> => {

  return customFetch<User>(getAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getProviderCallbackUrl = (provider: string,
    params: ProviderCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/${provider}/callback?${stringifiedParams}` : `/api/auth/${provider}/callback`
}

/**
 * @summary OAuth 回调：换码 → 取身份 → 查找/创建账户 → 签发会话 Cookie 并跳转前端。
 */
export const providerCallback = async (provider: string,
    params: ProviderCallbackParams, options?: Parameters<typeof customFetch>[1]): Promise<unknown> => {

  return customFetch<unknown>(getProviderCallbackUrl(provider,params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getProviderLoginUrl = (provider: string,) => {




  return `/api/auth/${provider}/login`
}

/**
 * @summary 跳转指定 OAuth 提供方的授权页；未注册的 provider 返回 404。
 */
export const providerLogin = async (provider: string, options?: Parameters<typeof customFetch>[1]): Promise<unknown> => {

  return customFetch<unknown>(getProviderLoginUrl(provider),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListWorkComputersUrl = () => {




  return `/api/work-computers`
}

export const listWorkComputers = async ( options?: Parameters<typeof customFetch>[1]): Promise<WorkComputer[]> => {

  return customFetch<WorkComputer[]>(getListWorkComputersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateWorkComputerUrl = () => {




  return `/api/work-computers`
}

export const createWorkComputer = async (createWorkComputerRequest: CreateWorkComputerRequest, options?: Parameters<typeof customFetch>[1]): Promise<WorkComputer> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<WorkComputer>(getCreateWorkComputerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createWorkComputerRequest)
  }
);}



export const getCreateConnectTokenUrl = () => {




  return `/api/work-computers/connect-token`
}

/**
 * @summary 生成/刷新当前用户的接入令牌（BRIER_TOKEN），供 CLI 隧道连接使用。
每用户仅保留一个活动令牌：再次调用即旧令牌失效。
 */
export const createConnectToken = async ( options?: Parameters<typeof customFetch>[1]): Promise<ConnectTokenResponse> => {

  return customFetch<ConnectTokenResponse>(getCreateConnectTokenUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getGetWorkComputerUrl = (computerId: WorkComputerId,) => {




  return `/api/work-computers/${computerId}`
}

export const getWorkComputer = async (computerId: WorkComputerId, options?: Parameters<typeof customFetch>[1]): Promise<WorkComputer> => {

  return customFetch<WorkComputer>(getGetWorkComputerUrl(computerId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getDeleteWorkComputerUrl = (computerId: WorkComputerId,) => {




  return `/api/work-computers/${computerId}`
}

/**
 * @summary 删除工作电脑（需本人；关联的 Agent 自动解除绑定）。
 */
export const deleteWorkComputer = async (computerId: WorkComputerId, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getDeleteWorkComputerUrl(computerId),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getListComputerAgentsUrl = (computerId: WorkComputerId,) => {




  return `/api/work-computers/${computerId}/agents`
}

/**
 * @summary 列出该工作电脑上绑定的 Agent（需本人）。
 */
export const listComputerAgents = async (computerId: WorkComputerId, options?: Parameters<typeof customFetch>[1]): Promise<Agent[]> => {

  return customFetch<Agent[]>(getListComputerAgentsUrl(computerId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListWorkspacesUrl = () => {




  return `/api/workspaces`
}

/**
 * @summary 列出当前用户的全部空间（需登录）。
 */
export const listWorkspaces = async ( options?: Parameters<typeof customFetch>[1]): Promise<Workspace[]> => {

  return customFetch<Workspace[]>(getListWorkspacesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateWorkspaceUrl = () => {




  return `/api/workspaces`
}

/**
 * @summary 创建空间（需登录）。
 */
export const createWorkspace = async (createWorkspaceRequest: CreateWorkspaceRequest, options?: Parameters<typeof customFetch>[1]): Promise<Workspace> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<Workspace>(getCreateWorkspaceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createWorkspaceRequest)
  }
);}



export const getGetWorkspaceUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}`
}

/**
 * @summary 获取工作空间详情（需登录 + 空间成员或创建者）。
 */
export const getWorkspace = async (workspaceId: WorkspaceId, options?: Parameters<typeof customFetch>[1]): Promise<Workspace> => {

  return customFetch<Workspace>(getGetWorkspaceUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListAgentsUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/agents`
}

export const listAgents = async (workspaceId: WorkspaceId, options?: Parameters<typeof customFetch>[1]): Promise<Agent[]> => {

  return customFetch<Agent[]>(getListAgentsUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateAgentUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/agents`
}

export const createAgent = async (workspaceId: WorkspaceId,
    createAgentRequest: CreateAgentRequest, options?: Parameters<typeof customFetch>[1]): Promise<Agent> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<Agent>(getCreateAgentUrl(workspaceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createAgentRequest)
  }
);}



export const getGetAgentUrl = (workspaceId: WorkspaceId,
    agentId: AgentId,) => {




  return `/api/workspaces/${workspaceId}/agents/${agentId}`
}

export const getAgent = async (workspaceId: WorkspaceId,
    agentId: AgentId, options?: Parameters<typeof customFetch>[1]): Promise<Agent> => {

  return customFetch<Agent>(getGetAgentUrl(workspaceId,agentId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getDeleteAgentUrl = (workspaceId: WorkspaceId,
    agentId: AgentId,) => {




  return `/api/workspaces/${workspaceId}/agents/${agentId}`
}

export const deleteAgent = async (workspaceId: WorkspaceId,
    agentId: AgentId, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getDeleteAgentUrl(workspaceId,agentId),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getUpdateAgentUrl = (workspaceId: WorkspaceId,
    agentId: AgentId,) => {




  return `/api/workspaces/${workspaceId}/agents/${agentId}`
}

export const updateAgent = async (workspaceId: WorkspaceId,
    agentId: AgentId,
    updateAgentRequest: UpdateAgentRequest, options?: Parameters<typeof customFetch>[1]): Promise<Agent> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<Agent>(getUpdateAgentUrl(workspaceId,agentId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateAgentRequest)
  }
);}



export const getListSessionsUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/sessions`
}

export const listSessions = async (workspaceId: WorkspaceId, options?: Parameters<typeof customFetch>[1]): Promise<Session[]> => {

  return customFetch<Session[]>(getListSessionsUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateSessionUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/sessions`
}

export const createSession = async (workspaceId: WorkspaceId,
    createSessionRequest: CreateSessionRequest, options?: Parameters<typeof customFetch>[1]): Promise<Session> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<Session>(getCreateSessionUrl(workspaceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createSessionRequest)
  }
);}



export const getDeleteSessionUrl = (workspaceId: WorkspaceId,
    sessionId: SessionId,) => {




  return `/api/workspaces/${workspaceId}/sessions/${sessionId}`
}

export const deleteSession = async (workspaceId: WorkspaceId,
    sessionId: SessionId, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getDeleteSessionUrl(workspaceId,sessionId),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getListMessagesUrl = (workspaceId: WorkspaceId,
    sessionId: SessionId,) => {




  return `/api/workspaces/${workspaceId}/sessions/${sessionId}/messages`
}

export const listMessages = async (workspaceId: WorkspaceId,
    sessionId: SessionId, options?: Parameters<typeof customFetch>[1]): Promise<SessionMessage[]> => {

  return customFetch<SessionMessage[]>(getListMessagesUrl(workspaceId,sessionId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getAppendMessageUrl = (workspaceId: WorkspaceId,
    sessionId: SessionId,) => {




  return `/api/workspaces/${workspaceId}/sessions/${sessionId}/messages`
}

export const appendMessage = async (workspaceId: WorkspaceId,
    sessionId: SessionId,
    appendMessageRequest: AppendMessageRequest, options?: Parameters<typeof customFetch>[1]): Promise<SessionMessage> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<SessionMessage>(getAppendMessageUrl(workspaceId,sessionId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(appendMessageRequest)
  }
);}



export const getListTasksUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/tasks`
}

export const listTasks = async (workspaceId: WorkspaceId, options?: Parameters<typeof customFetch>[1]): Promise<AgentTask[]> => {

  return customFetch<AgentTask[]>(getListTasksUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateTaskUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/tasks`
}

export const createTask = async (workspaceId: WorkspaceId,
    createTaskRequest: CreateTaskRequest, options?: Parameters<typeof customFetch>[1]): Promise<AgentTask> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<AgentTask>(getCreateTaskUrl(workspaceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTaskRequest)
  }
);}



export const getGetTaskUrl = (workspaceId: WorkspaceId,
    taskId: TaskId,) => {




  return `/api/workspaces/${workspaceId}/tasks/${taskId}`
}

export const getTask = async (workspaceId: WorkspaceId,
    taskId: TaskId, options?: Parameters<typeof customFetch>[1]): Promise<AgentTask> => {

  return customFetch<AgentTask>(getGetTaskUrl(workspaceId,taskId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCancelTaskUrl = (workspaceId: WorkspaceId,
    taskId: TaskId,) => {




  return `/api/workspaces/${workspaceId}/tasks/${taskId}/cancel`
}

export const cancelTask = async (workspaceId: WorkspaceId,
    taskId: TaskId, options?: Parameters<typeof customFetch>[1]): Promise<AgentTask> => {

  return customFetch<AgentTask>(getCancelTaskUrl(workspaceId,taskId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListTeamsUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/teams`
}

export const listTeams = async (workspaceId: WorkspaceId, options?: Parameters<typeof customFetch>[1]): Promise<AgentTeam[]> => {

  return customFetch<AgentTeam[]>(getListTeamsUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateTeamUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/teams`
}

export const createTeam = async (workspaceId: WorkspaceId,
    createTeamRequest: CreateTeamRequest, options?: Parameters<typeof customFetch>[1]): Promise<AgentTeam> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<AgentTeam>(getCreateTeamUrl(workspaceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTeamRequest)
  }
);}



export const getGetTeamUrl = (workspaceId: WorkspaceId,
    teamId: AgentTeamId,) => {




  return `/api/workspaces/${workspaceId}/teams/${teamId}`
}

export const getTeam = async (workspaceId: WorkspaceId,
    teamId: AgentTeamId, options?: Parameters<typeof customFetch>[1]): Promise<AgentTeam> => {

  return customFetch<AgentTeam>(getGetTeamUrl(workspaceId,teamId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListReposUrl = (provider: string,) => {




  return `/api/${provider}/repos`
}

/**
 * @summary 列出指定 provider 下当前用户的仓库（需登录 + 已绑定该 provider 令牌）。
未注册的 provider 返回 404；provider 有配置但未绑定令牌返回 Auth 错误。
 */
export const listRepos = async (provider: string, options?: Parameters<typeof customFetch>[1]): Promise<RepoInfo[]> => {

  return customFetch<RepoInfo[]>(getListReposUrl(provider),
  {
    ...options,
    method: 'GET'


  }
);}
