/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Brier API
 * AI Agent 工作空间平台
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from './custom-instance';
export interface CreateWorkspaceRequest {
  /** @nullable */
  auto_issue_assign?: boolean | null;
  /** @nullable */
  auto_pr_review?: boolean | null;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  instructions?: string | null;
  name: string;
  /** @nullable */
  repositories?: string[] | null;
  slug: string;
}

/**
 * 代码仓库信息（厂商 API 返回的仓库视图，非 Brier 领域概念）。
 * 与 `RepositoryProvider` 强绑定（trait 方法签名引用），故随契约同居本包；
 * 消费方仅限适配层（brier-forge）与应用层（brier-api）两端，不进 brier-type。
 */
export interface RepoInfo {
  full_name: string;
  name: string;
  private: boolean;
}

/**
 * 用户唯一标识
 */
export type UserId = string;

export type UserStatus = typeof UserStatus[keyof typeof UserStatus];


export const UserStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;

/**
 * 账户本体。第三方身份（OAuth）与本地凭证（手机号/密码）统一挂载在
 * `id`（用户 UUID）之下；password_hash 属敏感凭证，永不进入该 API 模型。
 */
export interface User {
  /** @nullable */
  avatar_url?: string | null;
  created_at: string;
  /** @nullable */
  email?: string | null;
  id: UserId;
  /** @nullable */
  last_login_at?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  phone?: string | null;
  status: UserStatus;
  updated_at: string;
  username: string;
}

/**
 * 工作空间唯一标识
 */
export type WorkspaceId = string;

export interface Workspace {
  auto_issue_assign: boolean;
  auto_pr_review: boolean;
  /** @nullable */
  avatar?: string | null;
  created_at: string;
  creator_id: UserId;
  /** @nullable */
  description?: string | null;
  id: WorkspaceId;
  /** @nullable */
  instructions?: string | null;
  name: string;
  repositories: string[];
  slug: string;
  updated_at: string;
}

export type ProviderCallbackParams = {
/**
 * OAuth 授权码（OAuth 回调携带的 query 参数）。
 */
code: string;
};

export type logoutResponse302 = {
  data: void
  status: 302
}

;
export type logoutResponseError = (logoutResponse302) & {
  headers: Headers;
};

export type logoutResponse = (logoutResponseError)

export const getLogoutUrl = () => {




  return `/api/auth/logout`
}

/**
 * @summary 登出：清除会话 Cookie 并跳转首页。
 */
export const logout = async ( options?: Parameters<typeof customFetch>[1]): Promise<logoutResponse> => {

  return customFetch<logoutResponse>(getLogoutUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type authMeResponse200 = {
  data: User
  status: 200
}

export type authMeResponse401 = {
  data: void
  status: 401
}

export type authMeResponseSuccess = (authMeResponse200) & {
  headers: Headers;
};
export type authMeResponseError = (authMeResponse401) & {
  headers: Headers;
};

export type authMeResponse = (authMeResponseSuccess | authMeResponseError)

export const getAuthMeUrl = () => {




  return `/api/auth/me`
}

/**
 * @summary 返回当前登录用户信息。
 */
export const authMe = async ( options?: Parameters<typeof customFetch>[1]): Promise<authMeResponse> => {

  return customFetch<authMeResponse>(getAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type providerCallbackResponse302 = {
  data: void
  status: 302
}

export type providerCallbackResponse401 = {
  data: void
  status: 401
}

export type providerCallbackResponse404 = {
  data: void
  status: 404
}

;
export type providerCallbackResponseError = (providerCallbackResponse302 | providerCallbackResponse401 | providerCallbackResponse404) & {
  headers: Headers;
};

export type providerCallbackResponse = (providerCallbackResponseError)

export const getProviderCallbackUrl = (provider: string,
    params: ProviderCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/${provider}/callback?${stringifiedParams}` : `/api/auth/${provider}/callback`
}

/**
 * @summary OAuth 回调：换码 → 取身份 → 查找/创建账户 → 签发会话 Cookie 并跳转前端。
 */
export const providerCallback = async (provider: string,
    params: ProviderCallbackParams, options?: Parameters<typeof customFetch>[1]): Promise<providerCallbackResponse> => {

  return customFetch<providerCallbackResponse>(getProviderCallbackUrl(provider,params),
  {
    ...options,
    method: 'GET'


  }
);}



export type providerLoginResponse302 = {
  data: void
  status: 302
}

export type providerLoginResponse404 = {
  data: void
  status: 404
}

;
export type providerLoginResponseError = (providerLoginResponse302 | providerLoginResponse404) & {
  headers: Headers;
};

export type providerLoginResponse = (providerLoginResponseError)

export const getProviderLoginUrl = (provider: string,) => {




  return `/api/auth/${provider}/login`
}

/**
 * @summary 跳转指定 OAuth 提供方的授权页；未注册的 provider 返回 404。
 */
export const providerLogin = async (provider: string, options?: Parameters<typeof customFetch>[1]): Promise<providerLoginResponse> => {

  return customFetch<providerLoginResponse>(getProviderLoginUrl(provider),
  {
    ...options,
    method: 'GET'


  }
);}



export type listWorkspacesResponse200 = {
  data: Workspace[]
  status: 200
}

export type listWorkspacesResponse401 = {
  data: void
  status: 401
}

export type listWorkspacesResponseSuccess = (listWorkspacesResponse200) & {
  headers: Headers;
};
export type listWorkspacesResponseError = (listWorkspacesResponse401) & {
  headers: Headers;
};

export type listWorkspacesResponse = (listWorkspacesResponseSuccess | listWorkspacesResponseError)

export const getListWorkspacesUrl = () => {




  return `/api/workspaces/`
}

/**
 * @summary 列出当前用户的全部空间（需登录）。
 */
export const listWorkspaces = async ( options?: Parameters<typeof customFetch>[1]): Promise<listWorkspacesResponse> => {

  return customFetch<listWorkspacesResponse>(getListWorkspacesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type createWorkspaceResponse200 = {
  data: Workspace
  status: 200
}

export type createWorkspaceResponse400 = {
  data: void
  status: 400
}

export type createWorkspaceResponse401 = {
  data: void
  status: 401
}

export type createWorkspaceResponseSuccess = (createWorkspaceResponse200) & {
  headers: Headers;
};
export type createWorkspaceResponseError = (createWorkspaceResponse400 | createWorkspaceResponse401) & {
  headers: Headers;
};

export type createWorkspaceResponse = (createWorkspaceResponseSuccess | createWorkspaceResponseError)

export const getCreateWorkspaceUrl = () => {




  return `/api/workspaces/`
}

/**
 * @summary 创建空间（需登录）。
 */
export const createWorkspace = async (createWorkspaceRequest: CreateWorkspaceRequest, options?: Parameters<typeof customFetch>[1]): Promise<createWorkspaceResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<createWorkspaceResponse>(getCreateWorkspaceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createWorkspaceRequest)
  }
);}



export type listReposResponse200 = {
  data: RepoInfo[]
  status: 200
}

export type listReposResponse401 = {
  data: void
  status: 401
}

export type listReposResponse404 = {
  data: void
  status: 404
}

export type listReposResponseSuccess = (listReposResponse200) & {
  headers: Headers;
};
export type listReposResponseError = (listReposResponse401 | listReposResponse404) & {
  headers: Headers;
};

export type listReposResponse = (listReposResponseSuccess | listReposResponseError)

export const getListReposUrl = (provider: string,) => {




  return `/api/${provider}/repos`
}

/**
 * @summary 列出指定 provider 下当前用户的仓库（需登录 + 已绑定该 provider 令牌）。
未注册的 provider 返回 404；provider 有配置但未绑定令牌返回 Auth 错误。
 */
export const listRepos = async (provider: string, options?: Parameters<typeof customFetch>[1]): Promise<listReposResponse> => {

  return customFetch<listReposResponse>(getListReposUrl(provider),
  {
    ...options,
    method: 'GET'


  }
);}
