/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Brier API
 * AI Agent 工作空间平台
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from './custom-instance';
/**
 * 用户唯一标识
 */
export type UserId = string;

/**
 * Agent 唯一标识
 */
export type AgentId = string;

export type PublicScope = typeof PublicScope[keyof typeof PublicScope];


export const PublicScope = {
  all: 'all',
  joined_spaces: 'joined_spaces',
  specified_spaces: 'specified_spaces',
} as const;

export type AgentStatus = typeof AgentStatus[keyof typeof AgentStatus];


export const AgentStatus = {
  online: 'online',
  offline: 'offline',
  connecting: 'connecting',
} as const;

export type AgentVisibility = typeof AgentVisibility[keyof typeof AgentVisibility];


export const AgentVisibility = {
  private: 'private',
  public: 'public',
} as const;

/**
 * 工作电脑唯一标识
 */
export type WorkComputerId = string;

/**
 * 工作空间唯一标识
 */
export type WorkspaceId = string;

export interface Agent {
  /** @nullable */
  color?: string | null;
  created_at: string;
  creator_id: UserId;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  icon?: string | null;
  id: AgentId;
  /** @nullable */
  last_active?: string | null;
  name: string;
  public_scope?: null | PublicScope;
  /** @nullable */
  runtime?: string | null;
  status: AgentStatus;
  updated_at: string;
  visibility: AgentVisibility;
  work_computer_id?: null | WorkComputerId;
  workspace_id: WorkspaceId;
}

/**
 * Agent 团队唯一标识
 */
export type AgentTeamId = string;

export type TeamMode = typeof TeamMode[keyof typeof TeamMode];


export const TeamMode = {
  coordinator: 'coordinator',
  sequential: 'sequential',
  graph: 'graph',
} as const;

export type TeamStatus = typeof TeamStatus[keyof typeof TeamStatus];


export const TeamStatus = {
  available: 'available',
  unavailable: 'unavailable',
} as const;

export interface AgentTeam {
  created_at: string;
  creator_id: UserId;
  /** @nullable */
  description?: string | null;
  id: AgentTeamId;
  mode: TeamMode;
  name: string;
  primary_agent_id?: null | AgentId;
  status: TeamStatus;
  updated_at: string;
  workspace_id: WorkspaceId;
}

export interface CreateAgentRequest {
  /** @nullable */
  color?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  icon?: string | null;
  name: string;
  public_scope?: null | PublicScope;
  /** @nullable */
  runtime?: string | null;
  visibility?: null | AgentVisibility;
  /** @nullable */
  work_computer_id?: string | null;
}

export interface CreateTeamRequest {
  /** @nullable */
  description?: string | null;
  mode?: null | TeamMode;
  name: string;
  /** @nullable */
  primary_agent_id?: string | null;
}

export type WorkComputerType = typeof WorkComputerType[keyof typeof WorkComputerType];


export const WorkComputerType = {
  local: 'local',
  ssh: 'ssh',
  cloud: 'cloud',
} as const;

export interface CreateWorkComputerRequest {
  computer_type: WorkComputerType;
  host: string;
  name: string;
  os: string;
}

export interface CreateWorkspaceRequest {
  /** @nullable */
  auto_issue_assign?: boolean | null;
  /** @nullable */
  auto_pr_review?: boolean | null;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  instructions?: string | null;
  name: string;
  /** @nullable */
  repositories?: string[] | null;
  slug: string;
}

/**
 * 代码仓库信息（厂商 API 返回的仓库视图，非 Brier 领域概念）。
 * 与 `RepositoryProvider` 强绑定（trait 方法签名引用），故随契约同居本包；
 * 消费方仅限适配层（brier-forge）与应用层（brier-api）两端，不进 brier-type。
 */
export interface RepoInfo {
  full_name: string;
  name: string;
  private: boolean;
}

export type UserStatus = typeof UserStatus[keyof typeof UserStatus];


export const UserStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;

/**
 * 账户本体。第三方身份（OAuth）与本地凭证（手机号/密码）统一挂载在
 * `id`（用户 UUID）之下；password_hash 属敏感凭证，永不进入该 API 模型。
 */
export interface User {
  /** @nullable */
  avatar_url?: string | null;
  created_at: string;
  /** @nullable */
  email?: string | null;
  id: UserId;
  /** @nullable */
  last_login_at?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  phone?: string | null;
  status: UserStatus;
  updated_at: string;
  username: string;
}

export type WorkComputerStatus = typeof WorkComputerStatus[keyof typeof WorkComputerStatus];


export const WorkComputerStatus = {
  online: 'online',
  offline: 'offline',
} as const;

export interface WorkComputer {
  computer_type: WorkComputerType;
  created_at: string;
  host: string;
  id: WorkComputerId;
  name: string;
  os: string;
  status: WorkComputerStatus;
  updated_at: string;
  user_id: UserId;
}

export interface Workspace {
  auto_issue_assign: boolean;
  auto_pr_review: boolean;
  /** @nullable */
  avatar?: string | null;
  created_at: string;
  creator_id: UserId;
  /** @nullable */
  description?: string | null;
  id: WorkspaceId;
  /** @nullable */
  instructions?: string | null;
  name: string;
  repositories: string[];
  slug: string;
  updated_at: string;
}

export type ProviderCallbackParams = {
/**
 * OAuth 授权码（OAuth 回调携带的 query 参数）。
 */
code: string;
};

export const getLogoutUrl = () => {




  return `/api/auth/logout`
}

/**
 * @summary 登出：清除会话 Cookie 并跳转首页。
 */
export const logout = async ( options?: Parameters<typeof customFetch>[1]): Promise<unknown> => {

  return customFetch<unknown>(getLogoutUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getAuthMeUrl = () => {




  return `/api/auth/me`
}

/**
 * @summary 返回当前登录用户信息。
 */
export const authMe = async ( options?: Parameters<typeof customFetch>[1]): Promise<User> => {

  return customFetch<User>(getAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getProviderCallbackUrl = (provider: string,
    params: ProviderCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/${provider}/callback?${stringifiedParams}` : `/api/auth/${provider}/callback`
}

/**
 * @summary OAuth 回调：换码 → 取身份 → 查找/创建账户 → 签发会话 Cookie 并跳转前端。
 */
export const providerCallback = async (provider: string,
    params: ProviderCallbackParams, options?: Parameters<typeof customFetch>[1]): Promise<unknown> => {

  return customFetch<unknown>(getProviderCallbackUrl(provider,params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getProviderLoginUrl = (provider: string,) => {




  return `/api/auth/${provider}/login`
}

/**
 * @summary 跳转指定 OAuth 提供方的授权页；未注册的 provider 返回 404。
 */
export const providerLogin = async (provider: string, options?: Parameters<typeof customFetch>[1]): Promise<unknown> => {

  return customFetch<unknown>(getProviderLoginUrl(provider),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListWorkComputersUrl = () => {




  return `/api/work-computers`
}

export const listWorkComputers = async ( options?: Parameters<typeof customFetch>[1]): Promise<WorkComputer[]> => {

  return customFetch<WorkComputer[]>(getListWorkComputersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateWorkComputerUrl = () => {




  return `/api/work-computers`
}

export const createWorkComputer = async (createWorkComputerRequest: CreateWorkComputerRequest, options?: Parameters<typeof customFetch>[1]): Promise<WorkComputer> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<WorkComputer>(getCreateWorkComputerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createWorkComputerRequest)
  }
);}



export const getGetWorkComputerUrl = (computerId: WorkComputerId,) => {




  return `/api/work-computers/${computerId}`
}

export const getWorkComputer = async (computerId: WorkComputerId, options?: Parameters<typeof customFetch>[1]): Promise<WorkComputer> => {

  return customFetch<WorkComputer>(getGetWorkComputerUrl(computerId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListWorkspacesUrl = () => {




  return `/api/workspaces`
}

/**
 * @summary 列出当前用户的全部空间（需登录）。
 */
export const listWorkspaces = async ( options?: Parameters<typeof customFetch>[1]): Promise<Workspace[]> => {

  return customFetch<Workspace[]>(getListWorkspacesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateWorkspaceUrl = () => {




  return `/api/workspaces`
}

/**
 * @summary 创建空间（需登录）。
 */
export const createWorkspace = async (createWorkspaceRequest: CreateWorkspaceRequest, options?: Parameters<typeof customFetch>[1]): Promise<Workspace> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<Workspace>(getCreateWorkspaceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createWorkspaceRequest)
  }
);}



export const getGetWorkspaceUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}`
}

/**
 * @summary 获取工作空间详情（需登录 + 空间成员或创建者）。
 */
export const getWorkspace = async (workspaceId: WorkspaceId, options?: Parameters<typeof customFetch>[1]): Promise<Workspace> => {

  return customFetch<Workspace>(getGetWorkspaceUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListAgentsUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/agents`
}

export const listAgents = async (workspaceId: WorkspaceId, options?: Parameters<typeof customFetch>[1]): Promise<Agent[]> => {

  return customFetch<Agent[]>(getListAgentsUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateAgentUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/agents`
}

export const createAgent = async (workspaceId: WorkspaceId,
    createAgentRequest: CreateAgentRequest, options?: Parameters<typeof customFetch>[1]): Promise<Agent> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<Agent>(getCreateAgentUrl(workspaceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createAgentRequest)
  }
);}



export const getGetAgentUrl = (workspaceId: WorkspaceId,
    agentId: AgentId,) => {




  return `/api/workspaces/${workspaceId}/agents/${agentId}`
}

export const getAgent = async (workspaceId: WorkspaceId,
    agentId: AgentId, options?: Parameters<typeof customFetch>[1]): Promise<Agent> => {

  return customFetch<Agent>(getGetAgentUrl(workspaceId,agentId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getDeleteAgentUrl = (workspaceId: WorkspaceId,
    agentId: AgentId,) => {




  return `/api/workspaces/${workspaceId}/agents/${agentId}`
}

export const deleteAgent = async (workspaceId: WorkspaceId,
    agentId: AgentId, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getDeleteAgentUrl(workspaceId,agentId),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getListTeamsUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/teams`
}

export const listTeams = async (workspaceId: WorkspaceId, options?: Parameters<typeof customFetch>[1]): Promise<AgentTeam[]> => {

  return customFetch<AgentTeam[]>(getListTeamsUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateTeamUrl = (workspaceId: WorkspaceId,) => {




  return `/api/workspaces/${workspaceId}/teams`
}

export const createTeam = async (workspaceId: WorkspaceId,
    createTeamRequest: CreateTeamRequest, options?: Parameters<typeof customFetch>[1]): Promise<AgentTeam> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<AgentTeam>(getCreateTeamUrl(workspaceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTeamRequest)
  }
);}



export const getGetTeamUrl = (workspaceId: WorkspaceId,
    teamId: AgentTeamId,) => {




  return `/api/workspaces/${workspaceId}/teams/${teamId}`
}

export const getTeam = async (workspaceId: WorkspaceId,
    teamId: AgentTeamId, options?: Parameters<typeof customFetch>[1]): Promise<AgentTeam> => {

  return customFetch<AgentTeam>(getGetTeamUrl(workspaceId,teamId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListReposUrl = (provider: string,) => {




  return `/api/${provider}/repos`
}

/**
 * @summary 列出指定 provider 下当前用户的仓库（需登录 + 已绑定该 provider 令牌）。
未注册的 provider 返回 404；provider 有配置但未绑定令牌返回 Auth 错误。
 */
export const listRepos = async (provider: string, options?: Parameters<typeof customFetch>[1]): Promise<RepoInfo[]> => {

  return customFetch<RepoInfo[]>(getListReposUrl(provider),
  {
    ...options,
    method: 'GET'


  }
);}
